dist: xenial

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

env:
  global:
    - WTFORMS="<=2.2.1"
  matrix:
    - SQLALCHEMY=1.2.9
    - SQLALCHEMY=1.3.5


# command to install dependencies
install:
  - "pip install WTForms$WTFORMS SQLAlchemy==$SQLALCHEMY"
  - "pip install ."
  - "pip install -r tests/requirements.txt"

# command to run tests
script: coverage run setup.py test
after_success:
  - pip install coveralls
  - coveralls
